#!/usr/bin/env bash

function delayedPluginInstall {
    sudo mkdir -p /home/developer/.IdeaIC2017.1/config/plugins
    sudo mkdir -p /home/developer/.IdeaIC2017.1/config/options
    sudo chown developer:developer -R /home/developer/.IdeaIC2017.1

    cd /home/developer/.IdeaIC2017.1/config/plugins/

    echo 'Installing MSA plugin'
    wget https://github.com/MontiSecArc/intellij_msa_language_plugin/releases/download/0.8.17/IntelliJ_MSA-0.8.17.zip -O msa.zip -q && unzip -q msa.zip && rm msa.zip

    echo 'Installing GraphDatabase plugin'
    wget https://github.com/MontiSecArc/graphdatabase/releases/download/1.0.5/GraphDatabase-1.0.5.zip -O GraphDatabasePlugin.zip -q && unzip -q GraphDatabasePlugin.zip && rm GraphDatabasePlugin.zip

    # Adding the predefined preferences to IDEA
    cp /home/developer/.jdk.table.xml /home/developer/.IdeaIC2017.1/config/options/jdk.table.xml
}

if [ ! -d /home/developer/.IdeaIC2017.1/config/plugins/IntelliJ_MSA ]; then
    # We are running with a non-Docker contained volume for IntelliJ prefs so we need to setup the plugin again
    delayedPluginInstall
fi

if [ -d /home/developer/.IdeaIC2017.1 ]; then
    # Ensure proper permissions
    sudo chown developer:developer -R /home/developer/.IdeaIC2017.1
fi
