#!/usr/bin/env bash

function delayedPluginInstall {
    sudo mkdir -p /home/developer/.IdeaIC2016.3/config/plugins
    sudo mkdir -p /home/developer/.IdeaIC2016.3/config/options
    sudo chown developer:developer -R /home/developer/.IdeaIC2016.3

    cd /home/developer/.IdeaIC2016.3/config/plugins/

    echo 'Installing MSA plugin'
    wget http://138.68.65.103:8081/artifactory/intellij_plugins_snapshot_local/de/monticore/lang/montisecarc/IntelliJ_Language_Plugin/0.8.0.SNAPSHOT/IntelliJ_Language_Plugin-0.7.11.SNAPSHOT.zip -O msa.zip -q && unzip -q msa.zip && rm msa.zip

    echo 'Installing GraphDatabase plugin'
    wget http://138.68.65.103:8081/artifactory/intellij_plugins_snapshot_local/de/tbuning/neo4j/graphdatabase/GraphDatabasePlugin/1.0.0/GraphDatabasePlugin-1.0.0.zip -O GraphDatabasePlugin.zip -q && unzip -q GraphDatabasePlugin.zip && rm GraphDatabasePlugin.zip

    echo 'Installing Graph Database Support plugin'
    wget https://plugins.jetbrains.com/files/8087/29684/GraphDatabaseSupport-2.2.0.zip -O graphdb.zip -q && unzip -q graphdb.zip && rm graphdb.zip

    # Adding the predefined preferences to IDEA
    cp /home/developer/.jdk.table.xml /home/developer/.IdeaIC2016.3/config/options/jdk.table.xml
}

if [ ! -d /home/developer/.IdeaIC2016.3/config/plugins/IntelliJ_MSA ]; then
    # We are running with a non-Docker contained volume for IntelliJ prefs so we need to setup the plugin again
    delayedPluginInstall
fi

if [ -d /home/developer/.IdeaIC2016.3 ]; then
    # Ensure proper permissions
    sudo chown developer:developer -R /home/developer/.IdeaIC2016.3
fi
